---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data-pvc
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nvmeof-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-logs-pvc
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  volumeName: rustfs-logs-pv
  storageClassName: zfs-configuration
