---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ollama
  namespace: &namespace ollama
spec:
  dependsOn:
    - name: ollama-config
      namespace: ollama
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/guarded
  interval: 1h
  path: ./kubernetes/apps/ollama/ollama/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: ollama-api
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: homelab-gitops
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
