---
# CNPG Cluster (instances=1) using the NVMe-oF SC
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mlflow-db
  namespace: ml
  annotations:
    fluxcd.io/redeploy: "2025-08-29T14:00:00"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 4Gi
  storage:
    size: 10Gi
    storageClass: nvmeof-fast
  bootstrap:
    initdb:
      database: mlflow
      owner: mlflow
      secret:
        name: postgres-secret
  monitoring:
    enablePodMonitor: true
