apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  name: kubeflow-pipelines-postgres-secret
                  key: username
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubeflow-pipelines-postgres-secret
                  key: password
