---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
  storage:
    size: 10Gi
    storageClass: nvmeof-fast
  bootstrap:
    initdb:
      database: litellm
      owner: litellm
      secret:
        name: litellm-postgres-secret
  monitoring:
    enablePodMonitor: true
