---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-gatus-endpoint
  labels:
    gatus.io/enabled: "true"
data:
  endpoints.yaml: |-
    endpoints:
      - name: litellm
        group: applications
        url: https://litellm.${SECRET_DOMAIN}/health/readiness
        interval: 1m
        conditions:
          - "[STATUS] == 200"
